name: neighbor
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.9
  - numpy
  - matplotlib
  - scipy
  - pandas
  - ase
  - ipywidgets
  - openpyxl
  - pip
  - pip:
      - py3Dmol
      - ipyfilechooser
      - plotly
      - IPython
      - ipympl
